version: '2.4'

services:
  web-server:
    image: nginx:latest
    container_name: pandora_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/usr/share/nginx/html/media:rw
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: django.Dockerfile
    container_name: pandora_app
    command: uwsgi --http 0.0.0.0:8000 --uid uwsgi --protocol uwsgi --wsgi pandora_x.wsgi:application --py-auto-reload 1
    volumes:
      - ./:/data/project
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
        - LINKEDIN_OAUTH_KEY=86302epa7w17ck
        - LINKEDIN_OAUTH_SECRET=DVRbHdTyRA2srA2m
        - GOOGLE_OAUTH_KEY=782858424709-h29sim71mnea99unbui9cjb61vffle1j.apps.googleusercontent.com
        - GOOGLE_OAUTH_SECRET=6YRqEOyAS-OIDFbJXX5t2a9B

  ws:
    build:
      context: .
      dockerfile: django.Dockerfile
    container_name: pandora_ws
    command: daphne -b 0.0.0.0 -p 8880 pandora_x.asgi:application
    volumes:
      - ./:/data/project
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  webpack:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: pandora_webpack
    command: npx webpack
    volumes:
      - ./webpack.config.js:/data/project/webpack.config.js:ro
      - ./dev:/data/project/dev:ro
      - ./static:/data/project/static:rw

  db:
    image: mysql:8
    container_name: pandora_db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pandora_x
    volumes:
      - ./initial_database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    container_name: pandora_redis
    image: redis:latest
