version: '2.4'

services:
  web-server:
    image: nginx:latest
    container_name: pandora_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/usr/share/nginx/html/media:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: django.Dockerfile
    container_name: pandora_app
    command: uwsgi --http 0.0.0.0:8000 --uid uwsgi --protocol uwsgi --wsgi pandora_x.wsgi:application --py-auto-reload 1
    volumes:
      - ./:/data/project
    depends_on:
      db:
        condition: service_healthy
    environment:
        - LINKEDIN_OAUTH_KEY=772wb269hjt4pw
        - LINKEDIN_OAUTH_SECRET=ihpH92PHWrvns60y
        - GOOGLE_OAUTH_KEY=300053737638-h1rhiev4aqvbd0rha4ckohi2cem1vqoq.apps.googleusercontent.com
        - GOOGLE_OAUTH_SECRET=e31iQBtrk48oH64N33K2Nq2H

  db:
    image: mysql:5.7
    container_name: pandora_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pandora_x
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
