# Generated by Django 2.2.3 on 2019-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_auto_20190922_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.FileField(upload_to='badge_icons/'),
        ),
    ]
