# Generated by Django 2.2.3 on 2019-09-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Direct'), (1, 'Budget'), (2, 'Recognition'), (3, 'Redeem')])),
                ('source_object_id', models.PositiveIntegerField()),
                ('destination_object_id', models.PositiveIntegerField()),
                ('point_amount', models.PositiveIntegerField()),
                ('destination_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_content_type', to='contenttypes.ContentType')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_content_type', to='contenttypes.ContentType')),
            ],
        ),
    ]
