# Generated by Django 2.2.3 on 2019-10-28 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_space'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
