# Generated by Django 2.2.3 on 2019-10-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badge', '0004_badgelog'),
        ('space', '0002_auto_20190923_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_set', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_activity_set', to=settings.AUTH_USER_MODEL)),
                ('recognition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badge.BadgeLog')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Space')),
            ],
        ),
    ]
