# Generated by Django 2.2.3 on 2019-10-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20190923_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='budget_point_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='earned_point_amount',
        ),
    ]
