# Generated by Django 2.2.3 on 2019-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20191028_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
